version: '3.8'

services:
  server:
    build:
      context: ./server
    ports:
      - "8080:8080"
    volumes:
      - ./server:/app
    restart: always

  sender:
      build:
        context: ./sender
      depends_on:
        - server
      restart: always
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:80"
    volumes:
      - ./frontend:/usr/share/nginx/html
    restart: always

  