version: '3.8'

services:
  server:
    build:
      context: ./server
    ports:
      - "8080:8080"
    volumes:
      - ./server:/app
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 5s
      timeout: 3s
      retries: 5

  sender:
    build:
      context: ./sender
    volumes:
      - ./sender:/app  # Mount the sender directory into the container
    depends_on:
      server:
        condition: service_healthy
    restart: always
    
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:80"
    volumes:
      - ./frontend:/usr/share/nginx/html
    restart: always